services:
  - type: web
    name: academic-faq-chatbot
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: chmod +x build.sh start.sh && ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: GEMINI_API_KEY
        sync: false  # Must be set manually in Render dashboard
      - key: RENDER
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
